### PR TITLE
windows ci tests

### LINKED ISSUE #61: setup CI for automated tests on Windows

### PR DESCRIPTION
**Pull request by sudiptob2**
closes #61

### CODE REVIEW

**Comment by sudiptob2** [comment]
Installed `pipenv install atomicwrites` because pytest depends on this library and can not find otherwise.

**Comment by 0hsn** [comment]
> Installed `pipenv install atomicwrites` because pytest depends on this library and can not find otherwise.

any particular reason to not use `--dev` flag?

**Comment by sudiptob2** [comment]
> > Installed `pipenv install atomicwrites` because pytest depends on this library and can not find otherwise.
> 
> any particular reason to not use `--dev` flag?

No particular reason, is --dev necessary in this case?

**Comment by 0hsn** [comment]
> No particular reason, is --dev necessary in this case?

Okay so, if you need this packaged when `chk` is running, then you do not use [`--dev`](https://pipenv-fork.readthedocs.io/en/latest/basics.html#pipenv-install)

**Comment by sudiptob2** [comment]
> * Okay so, if you need this packaged when `chk` is running, then you do not use [`--dev`](https://pipenv-fork.readthedocs.io/en/latest/basics.html#pipenv-install)
> * Also, I am unsure of what this package does in this context.

I am not totally sure what this package does, but without this `pytest` can not run. 
I understand that putting `--dev` improves readability and provides an indication that the package is a dev dependency. So, we can add `--dev` here. 
I thought adding `--dev` flag has no significance in test pipelines because this pipeline environment is solely created for running the tests.

**Comment by 0hsn** [comment]
> I thought adding --dev flag has no significance in test pipelines because this pipeline environment is solely created for running the tests.

correct

> I understand that putting --dev improves readability and provides an indication that the package is a dev dependency. So, we can add --dev here.

correct

**Review by 0hsn — APPROVED** [review]

**Pull request merged**
